
FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

RUN npm install

COPY apps ./apps
COPY packages ./packages

RUN npm run db:generate

RUN npm run build-bank-server

EXPOSE 3001

CMD ["npm","run","start-bank-server"]