apiVersion: apps/v1
kind: Deployment
metadata:
  name: payzen
  labels:
    app: payzen
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payzen
  template:
    metadata:
      labels:
        app: payzen
    spec:
      containers:
      - name: payzen
        image: royaals28/payzenwallets:linux
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: DATABASE_URL
          value: "Replace with your Cloud PostgreSQL Database URL"
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"

